{% set name = "ChemSpiPy" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7d0720b95c871ca8f86e771c4894548f1378bd201e9333b81725fefd6bcd92ff

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - six

test:
  imports:
    - chemspipy

about:
  home: https://github.com/mcs07/ChemSpiPy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python wrapper for the ChemSpider API'
  description: |
    ChemSpiPy provides a way to interact with ChemSpider in Python. 
    It allows chemical searches, chemical file downloads, depiction 
    and retrieval of chemical properties.
  doc_url: https://chemspipy.readthedocs.io/
  dev_url: https://github.com/mcs07/ChemSpiPy

extra:
  recipe-maintainers:
    - mcs07
