travis:
  secure:
    BINSTAR_TOKEN: r0PJcKKQ4sE0/RBSkZrLL/asQINhCpA8jypp6Sx3qf4x8ypK19+9Jp9/ymAE5hXbkDxtIYzsEyFWQQi0UaZfA/HcuNyt6PPJ0rvd3NSTgHnga3OWh7mU+mgTcSsJ7J8S+WOhEEz9oeSuYM9IqwpUAs9qoNklKgvdbM8LZZ9q3FmyZvFUI2icREVaiNbrJu30xwFVmE9mB9i8zR3zmY2eN8/7N0zc67eRJIsclZoAGcVrOiyB4hoj3XWRF+frF8Rjih3T9OlrC7Ftw96Nho52yZTyAkR/7jiGLYX22h2jgVdcKxGcbcX1+YiLMiIzmq0c8nbyW/qu2XjBno0wOQBXqyHVI1T3APo0OTHot2BeIFLc4zbCsHXvLXX6/fThDQDsw5hhALNvHveOupVX3Ln2Beaersm5ohO9mQdfwF/dKTpu4NBZs/tdOjR5hA13vZDnWa80hFIrN7rEwUjZsH0tPYX8BhpYpvaU3QUbca8u9zFpkpG7BQUjEQQ5klTxfvyCjvFOw70UbfhrSRZfWCT/nAMcCiH/+YFP8dZRZ0lbjNzNvoDV/Z7hpgWuxsQmkU2w5HkY4DqznDNc0tsIBwXLS/IMSVKy4+RNrixjhlqYXeq/Uff4cueGTSxsHu4D2/awublvVhl/FQVc8ufgVL64YJfJSDtUsrW1Z5ESp8ozYC4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
